# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 00:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import remostars.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maximum of 50 characters.', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL automatically generated from the title.', unique=True)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logos')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubHonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('achievement', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ClubIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('draws', models.PositiveIntegerField()),
                ('loss', models.PositiveIntegerField()),
                ('goals_for', models.PositiveIntegerField()),
                ('goals_against', models.PositiveIntegerField()),
                ('goals_difference', models.IntegerField()),
                ('points', models.PositiveIntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remostars.Club')),
            ],
            options={
                'ordering': ['-points', '-goals_difference', '-goals_for', 'club'],
                'verbose_name': 'Club Rank',
                'verbose_name_plural': 'Club Ranks',
            },
        ),
        migrations.CreateModel(
            name='ClubOfficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='officials')),
                ('position', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True, help_text='Uncheck this if the Official is no longer with the club.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(help_text='E.g: NPFL Matchday 1', max_length=50)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField(default=remostars.models.default_start_time, help_text='Default is 16:00:00 for 4p.m.')),
                ('venue', models.CharField(help_text='Name and Location of the Stadium, E.g. Teslim Balogun Stadium, Lagos.', max_length=50)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_away_team', to='remostars.Club')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_home_team', to='remostars.Club')),
            ],
            options={
                'ordering': ['match_date'],
                'get_latest_by': 'match_date',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='gallery')),
                ('caption', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('squad_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='players')),
                ('position', models.CharField(choices=[('GOALKEEPER', 'Goalkeeper'), ('DEFENDER', 'Defender'), ('MIDFIELDER', 'Midfielder'), ('STRIKER', 'Striker')], max_length=15)),
                ('club_appearances', models.PositiveIntegerField(blank=True, help_text='Total club appearances since joining the club.')),
                ('goals', models.PositiveIntegerField(blank=True, help_text='Total goals since joining the club.', null=True)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('yellow_cards', models.PositiveIntegerField(blank=True, help_text='Total yellow cards since joining the club.', null=True)),
                ('red_cards', models.PositiveIntegerField(blank=True, help_text='Total red cards since joining the club.', null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height', models.CharField(blank=True, help_text='Height in cm.', max_length=10)),
                ('weight', models.CharField(blank=True, help_text='Weight in kg.', max_length=10)),
                ('previous_clubs', models.CharField(blank=True, max_length=255)),
                ('biography', ckeditor.fields.RichTextField()),
                ('active', models.BooleanField(default=True, help_text='Uncheck this if the Player is no longer with the club.')),
            ],
            options={
                'ordering': ['squad_number'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images')),
                ('caption', models.CharField(blank=True, help_text='Image Caption. Optional', max_length=200)),
                ('excerpt', models.TextField(help_text='Summary of the Blog Post.')),
                ('body', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='remostars.Category')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(help_text='E.g: NPFL Matchday 1', max_length=50)),
                ('home_team_score', models.PositiveIntegerField()),
                ('away_team_score', models.PositiveIntegerField()),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField(default=remostars.models.default_start_time, help_text='Default is 16:00:00 for 4p.m.')),
                ('venue', models.CharField(help_text='Name and Location of the Stadium, E.g. Teslim Balogun Stadium, Lagos.', max_length=50)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_away_team', to='remostars.Club')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_home_team', to='remostars.Club')),
            ],
            options={
                'ordering': ['-match_date'],
                'get_latest_by': 'match_date',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='sponsors')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearances', models.PositiveIntegerField(default=0, help_text='Total appearances in a season.')),
                ('goals', models.PositiveIntegerField(default=0, help_text='Total goals in a season.')),
                ('yellow_cards', models.PositiveIntegerField(default=0, help_text='Total yellow cards in a season.')),
                ('red_cards', models.PositiveIntegerField(default=0, help_text='Total red cards in a season.')),
                ('active', models.BooleanField(default=True, help_text='Uncheck this if the player is no longer with the club.')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='remostars.Player')),
            ],
            options={
                'ordering': ['player'],
            },
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('embed_link', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
